name: code-quality

on:
  [push]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.8.5']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install quality packages
        run: pip install .[quality]
      - name: run quality checks
        run: make quality
